job:
  image: 'hmctspublic.azurecr.io/am/judicial-booking-batch-service:latest'
  ingressHost: am-judicial-booking-batch-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4081
  aadIdentityName: am
  kind: job
  global:
    jobKind: job
postgres:
  enabled: false
metadata:
  name: judicialBookingRefresh
spec:
  template:
    spec:
      containers:
        - name: pi
          image: 'hmctspublic.azurecr.io/am/judicial-booking-batch-service:latest'
      restartPolicy: Never
  backoffLimit: 4
